jobs:
  - name: sample_node_runCI
    type: runCI
    steps:
      - IN: nightly-trigger
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: sampleApp_runCI
    type: runCI
    steps:
      - OUT: app_img
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  - name: sampleapp-man
    type: manifest
    steps:
      - IN: app_img

  - name: sampleapp-deploy
    type: deploy
    steps:
      - IN: sampleapp-man
      - IN: ddc-cluster