jobs:
  - name: build-app
    type: runCLI
    steps:
      - IN: sampleapp_repo
      - IN: dockerhub
      - OUT: app-img
      - TASK:
        - script: printenv
        - script: ./IN/sampleapp_repo/gitRepo/build.sh
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('

  # - name: bat_runCI
  #   type: runCI
  #   steps:
  #     - IN: bat_params
  #     - IN: sampleapp-deploy

  - name: sampleapp-man
    type: manifest
    steps:
      - IN: options
      - IN: app-img
        force: true
        versionName: latest


  - name: sampleapp-deploy
    type: deploy
    steps:
      - IN: sampleapp-man
        force: true
      - IN: ddc-cluster
