jobs:
  - name: sample_node_runCI
    type: runCLI
    steps:
      - IN: nightly-trigger
    on_success:
      - script: echo 'on success !!!!!'
    on_failure:
      - script: echo 'Failed job .... :('
